### ISSUE TITLE
cannot push image 

### ISSUE THREAD

**Issue by wychl** [uber/kraken#164] opened 2019-05-27 05:09 UTC
time="2019-05-27T03:49:32.573187371Z" level=error msg="response completed with error" err.code=unknown err.detail="uploads are disabled" err.message="unknown error" go.version=go1.11.4 http.request.host=registry-backend http.request.id=adde9e4d-173e-4b0a-b664-876ed7620dac http.request.method=POST http.request.remoteaddr=172.17.0.1 http.request.uri="/v2/library/redis/blobs/uploads/" http.request.useragent="docker/18.09.4 go/go1.10.8 git-commit/d14af54 kernel/4.15.0-50-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.4 \(linux\))" http.response.contenttype="application/json" http.response.duration=7.410565ms http.response.status=500 http.response.written=70 vars.name="library/redis"
@ - - [27/May/2019:03:49:32 +0000] "POST /v2/library/redis/blobs/uploads/ HTTP/1.0" 500 70 "" "docker/18.09.4 go/go1.10.8 git-commit/d14af54 kernel/4.15.0-50-generic os/linux arch/amd64 UpstreamClient(Docker-Client/18.09.4 \\(linux\\))"

**Comment by yiranwang52** [comment] 2019-05-28 00:59
duplicate of #165

**Closed by yiranwang52** 2019-05-28 00:59 UTC
Labels: duplicate
